# fly.toml app configuration file generated for lrh-signature-server on 2025-07-30T15:23:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lrh-signature-server'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="signature_cache"
  destination="/usr/src/app/cache"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
